2025-09-14 12:22:19,513 INFO    MainThread:902343 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-09-14 12:22:19,513 INFO    MainThread:902343 [wandb_setup.py:_flush():70] Configure stats pid to 902343
2025-09-14 12:22:19,514 INFO    MainThread:902343 [wandb_setup.py:_flush():70] Loading settings from /home/aiotlab/.config/wandb/settings
2025-09-14 12:22:19,514 INFO    MainThread:902343 [wandb_setup.py:_flush():70] Loading settings from /mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod/wandb/settings
2025-09-14 12:22:19,514 INFO    MainThread:902343 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-09-14 12:22:19,514 INFO    MainThread:902343 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod/wandb/run-20250914_122219-hbpol4qr/logs/debug.log
2025-09-14 12:22:19,514 INFO    MainThread:902343 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod/wandb/run-20250914_122219-hbpol4qr/logs/debug-internal.log
2025-09-14 12:22:19,514 INFO    MainThread:902343 [wandb_init.py:init():852] calling init triggers
2025-09-14 12:22:19,514 INFO    MainThread:902343 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'num_folds': 0, 'seed': 3407, 'cuda': 0, 'epochs': 20, 'batch_size': 64, 'lr': 0.0003, 'weight_decay': 0.05, 'optimizer': 'AdamW', 'clip_value': 1, 'dropout': 0.1, 'classifier': 'all_patch_reps', 'downstream_dataset': 'PEARL', 'datasets_dir': '/mnt/disk1/aiotlab/namth/EEGFoundationModel/datasets/pearl', 'num_of_classes': 2, 'model_dir': './data/wjq/models_weights/Big/BigFaced', 'num_workers': 16, 'label_smoothing': 0.1, 'multi_lr': False, 'frozen': False, 'use_pretrained_weights': True, 'foundation_dir': 'pretrained_weights/pretrained_weights.pth', '_wandb': {}}
2025-09-14 12:22:19,514 INFO    MainThread:902343 [wandb_init.py:init():893] starting backend
2025-09-14 12:22:19,514 INFO    MainThread:902343 [wandb_init.py:init():897] sending inform_init request
2025-09-14 12:22:19,520 INFO    MainThread:902343 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-09-14 12:22:19,520 INFO    MainThread:902343 [wandb_init.py:init():907] backend started and connected
2025-09-14 12:22:19,524 INFO    MainThread:902343 [wandb_init.py:init():1005] updated telemetry
2025-09-14 12:22:19,530 INFO    MainThread:902343 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-09-14 12:22:20,252 INFO    MainThread:902343 [wandb_init.py:init():1104] starting run threads in backend
2025-09-14 12:22:20,762 INFO    MainThread:902343 [wandb_run.py:_console_start():2573] atexit reg
2025-09-14 12:22:20,762 INFO    MainThread:902343 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-09-14 12:22:20,762 INFO    MainThread:902343 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-09-14 12:22:20,762 INFO    MainThread:902343 [wandb_run.py:_redirect():2513] Redirects installed.
2025-09-14 12:22:20,764 INFO    MainThread:902343 [wandb_init.py:init():1150] run started, returning control to user process
2025-09-14 12:25:28,087 INFO    MsgRouterThr:902343 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-09-14 12:25:29,480 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,483 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,485 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,487 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,489 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,490 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,492 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,494 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,495 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,497 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,499 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,500 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,502 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,504 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,506 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,509 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,511 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,513 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,515 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,517 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,519 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,521 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,523 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,525 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,527 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,529 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,531 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,533 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,534 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 12:25:29,536 ERROR   MainThread:902343 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
