2025-09-14 11:56:57,441 INFO    MainThread:872356 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-09-14 11:56:57,442 INFO    MainThread:872356 [wandb_setup.py:_flush():70] Configure stats pid to 872356
2025-09-14 11:56:57,442 INFO    MainThread:872356 [wandb_setup.py:_flush():70] Loading settings from /home/aiotlab/.config/wandb/settings
2025-09-14 11:56:57,442 INFO    MainThread:872356 [wandb_setup.py:_flush():70] Loading settings from /mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod/wandb/settings
2025-09-14 11:56:57,442 INFO    MainThread:872356 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-09-14 11:56:57,442 INFO    MainThread:872356 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod/wandb/run-20250914_115657-lpxzm5y3/logs/debug.log
2025-09-14 11:56:57,442 INFO    MainThread:872356 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod/wandb/run-20250914_115657-lpxzm5y3/logs/debug-internal.log
2025-09-14 11:56:57,442 INFO    MainThread:872356 [wandb_init.py:init():852] calling init triggers
2025-09-14 11:56:57,443 INFO    MainThread:872356 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'num_folds': 0, 'seed': 3407, 'cuda': 0, 'epochs': 20, 'batch_size': 64, 'lr': 0.0003, 'weight_decay': 0.05, 'optimizer': 'AdamW', 'clip_value': 1, 'dropout': 0.1, 'classifier': 'all_patch_reps', 'downstream_dataset': 'PEARL', 'datasets_dir': '/mnt/disk1/aiotlab/namth/EEGFoundationModel/datasets/pearl', 'num_of_classes': 2, 'model_dir': './data/wjq/models_weights/Big/BigFaced', 'num_workers': 16, 'label_smoothing': 0.1, 'multi_lr': False, 'frozen': False, 'use_pretrained_weights': True, 'foundation_dir': 'pretrained_weights/pretrained_weights.pth', '_wandb': {}}
2025-09-14 11:56:57,443 INFO    MainThread:872356 [wandb_init.py:init():893] starting backend
2025-09-14 11:56:57,443 INFO    MainThread:872356 [wandb_init.py:init():897] sending inform_init request
2025-09-14 11:56:57,450 INFO    MainThread:872356 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-09-14 11:56:57,450 INFO    MainThread:872356 [wandb_init.py:init():907] backend started and connected
2025-09-14 11:56:57,453 INFO    MainThread:872356 [wandb_init.py:init():1005] updated telemetry
2025-09-14 11:56:57,461 INFO    MainThread:872356 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-09-14 11:56:58,682 INFO    MainThread:872356 [wandb_init.py:init():1104] starting run threads in backend
2025-09-14 11:56:59,411 INFO    MainThread:872356 [wandb_run.py:_console_start():2573] atexit reg
2025-09-14 11:56:59,412 INFO    MainThread:872356 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-09-14 11:56:59,412 INFO    MainThread:872356 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-09-14 11:56:59,412 INFO    MainThread:872356 [wandb_run.py:_redirect():2513] Redirects installed.
2025-09-14 11:56:59,414 INFO    MainThread:872356 [wandb_init.py:init():1150] run started, returning control to user process
2025-09-14 11:59:30,650 INFO    MsgRouterThr:872356 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-09-14 11:59:32,429 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,434 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,436 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,438 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,440 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,442 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,443 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,445 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,447 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,448 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,450 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,452 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,454 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,455 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,457 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,459 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,461 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,463 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,464 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,467 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,468 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,470 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,472 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,474 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,475 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,477 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,479 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,480 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,482 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-14 11:59:32,484 ERROR   MainThread:872356 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/aiotlab/miniconda3/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
